# Joyread YAML config

server:
    port: 8080
    asset_path: .
    database:
        type: postgresql # postgresql/mysql/sqlite3
        hostname: localhost # localhost/23.253.231.169
        port: 5432 # 5432/3306
        name: joyread # joyreaddb
        username: postgres # joyreaduser
        password: postgres
        sslmode: disable # only applicable for postgresql